### ISSUE TITLE
Disable HTML parsing in code blocks

### ISSUE THREAD

**Issue by amercier** [h13i32maru/esdoc#12]
While parsing the following docblock:

```
/**
 * Usage
 * -----
 * 
 *     <div id="pg">
 *       <div data-pagination-value>1</div>
 *       of
 *       <div data-pagination-max>10</div>
 *     </div>
 */
```

ESDoc replaces all code containing HTML elements by actual HTML elements, which is undesired in a code block:

![screen shot 2015-06-13 at 12 18 47 pm](https://cloud.githubusercontent.com/assets/1246795/8145678/72ace618-11c6-11e5-821b-5e7470dc44e7.png)

Is there a way to achieve this in another way (I tried with triple backquotes, same issue), or disable HTML in comments entirely?

**Comment by h13i32maru** [comment]
@amercier Hi! Thank you for reporting issue.
This is the bug of ESDoc. I will try to fix the bug that it can use triple backquotes.

**Comment by h13i32maru** [comment]
@amercier I fixed this bug. I will release the fixing in next version.

**Comment by amercier** [comment]
:+1:
