### ISSUE TITLE
Custom template?

### ISSUE THREAD

**Issue by stefanwalther** [h13i32maru/esdoc#16]
Hi, great work!

Any plans to extend Esdoc to be able to render using custom templates?

**Comment by h13i32maru** [comment]
@stefanwalther Hi, thank you :smile: 
Now, ESDoc supports to include js/css in output HTML.([config.scripts/config.styles](https://esdoc.org/config.html)).

And I plan to provide 2 hook points.
- after parsing tag(you can handle meta data)
- after building document(you can handle HTML)

I think that full scratch custom templates are very high cost to template owner.
And keeping high quality with using it is very hard.
So, for now, I do not plan to it officially.

Will this answer help you?

**Comment by stefanwalther** [comment]
Yes, thx ... looking forward to see more possibilities to customize ...

**Comment by h13i32maru** [comment]
@stefanwalther ESDoc supports plugin feature. see https://esdoc.org/api.html#plugin-feature for more information.
