### ISSUE TITLE
Use a more complete console logging solution?

### ISSUE THREAD

**Issue by bucaran** [h13i32maru/esdoc#18]
Would you be interested in using a more complete logging solution? 

There is `chalk` which is the most popular, I could help you integrate it.

There is also my own [`clor`](https://github.com/bucaran/clor), which is just 30 lines of code.

Cheers

**Comment by h13i32maru** [comment]
@bucaran Hi
ESDoc uses [color-logger](https://github.com/h13i32maru/color-logger).
