### ISSUE TITLE
Handle ES6 module exports, with class reference (Feature Request)

### ISSUE THREAD

**Issue by mmoss** [h13i32maru/esdoc#19]
I was hoping to be able to encapsulate modules which are made up of a file which only export a single instance of a class (without the class being exported). Any chance of adding `@module` support for better ES6 module export handling? JSDoc handles it [this way](http://usejsdoc.org/tags-module.html) or [this way](http://usejsdoc.org/tags-exports.html). I'd love to chip in, just let me know if you'd be willing to accept a pull request if I added a test case for the new tag (and if I'd also need to file a PR for updating the documentation/website). ありがとう！

Example use case:
```js
class Foo {}

/**
 * @type Foo
 * @module fooSingletonInstance
 */
export const fooSingletonInstance = new Foo();
```

**Comment by h13i32maru** [comment]
ESDoc head revision supports the following pattern.

```javascript
// default export
class Foo {}
export default new Foo();

// named export
class Bar{}
let bar = new Bar();
export {bar};
```

And I plan to support the following pattern without any tag.
```javascript
class Foo {}
export const foo = new Foo();
```

Documentation of this pattern shows ``Foo`` class and [caution](https://cloud.githubusercontent.com/assets/985170/8422613/edb024ba-1f18-11e5-905e-a3bd041e708d.png)

**Comment by mmoss** [comment]
Awesome! Looks great.

**Comment by h13i32maru** [comment]
@mmoss ESDoc supports instance exporting. I will release it in next version.
