### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by yamalight** [h13i32maru/esdoc#2]
Any plans for it? (since babel supports it out of the box anyway)

**Comment by h13i32maru** [comment]
Sorry, for now, I do not plan that support JSX :sweat:

**Comment by yamalight** [comment]
@h13i32maru alright. would be interested in PR with it? maybe I'll fork and try to implement it myself :)

**Comment by h13i32maru** [comment]
@yamalight I am not interested in the PR. Because I am not using JSX and can not maintain it. I welcome that you fork and implement it!

**Comment by yamalight** [comment]
@h13i32maru alright, fair enough. thanks for responses :)

**Comment by h13i32maru** [comment]
@yamalight ESDoc supported JSX!
I had thought the support of JSX is difficult. However, espree already supports JSX.
Sorry, I was careless :sweat_drops:

**Comment by yamalight** [comment]
ah, cool. I'll try to use it on my jsx code one more and will report if there are any issues :+1:

**Comment by resistdesign** [comment]
@yamalight Any news?

**Comment by yamalight** [comment]
@resistdesign no issues so far, works great

**Comment by resistdesign** [comment]
@yamalight Does it auto-doc your props based on `static propTypes`?

**Comment by yamalight** [comment]
@resistdesign no, it doesn't have any jsx specific functions (although that does sounds pretty cool)

**Comment by realmike33** [comment]
@resistdesign Still getting an error when trying to parse jsx. Not sure what @yamalight solution to this was.

**Comment by resistdesign** [comment]
@realmike33 I haven't tried in a while, been handling other stuff for now.

**Comment by winjer** [comment]
Any progress on this?  It seems to be fine with ES6 syntax, but isn't parsing files with a .jsx extension, so just adding that might be sufficient to get this working completely?

**Comment by winjer** [comment]
If anyone else comes to this, you should do something like this for your configuration, and it works pretty well:

`{
    "source": "./src",
    "destination": "./doc",
    "includes": [".*\\.js", ".*\\.jsx"],
    "index": "./README.md",
    "package": "./package.json",
    "experimentalProposal": {
        "classProperties": true,
        "objectRestSpread": true
    }
}`

**Comment by jarzuaga** [comment]
@yamalight would you mind sharing an example of some jsx annotated with esdoc tag?

**Comment by yamalight** [comment]
@jarzuaga I'm just using it normally within react projects (generating docs for react classes) - seems to work just fine without any additional tweaks.

**Comment by jarzuaga** [comment]
Gotcha, thought you were annotating the JSX in some way and got curious. Thanks @yamalight !

**Comment by 11111000000** [comment]
now youre need to use plugin instead
