### ISSUE TITLE
structured index (multilevel folder)

### ISSUE THREAD

**Issue by daniele-zurico** [h13i32maru/esdoc#21]
Hi guys,
we've written a small function that generate the documentation in different folder (not just a flax index).
The visual result is something like that:
root:
  folder1:
    file1
  folder2:
   folder2.1:
    file2

this is our source code:
https://github.com/daniele-zurico/es6-webpack-angular/blob/master/vendor/doc-menu.js
https://github.com/daniele-zurico/es6-webpack-angular/blob/master/vendor/doc-style.css

https://github.com/daniele-zurico/es6-webpack-angular/blob/master/esdoc.json
{
  "source": "./app",
  "destination": "./target/docs",
  "autoPrivate": true,
  "scripts": ["./vendor/doc-menu.js", "./bower_components/jquery/dist/jquery.min.js", "./vendor/jstorage.min.js"],
  "styles": ["./vendor/doc-style.css", "./vendor/font-awesome-4.3.0/css/font-awesome.min.css"]
}

**Comment by h13i32maru** [comment]
@daniele-zurico Hi!
This menu is awesome :sparkles: 
I will reference this menu for future improvement :smile: 

Thank you.

**Comment by daniele-zurico** [comment]
You're welcome! if you need same support let me know!

**Comment by h13i32maru** [comment]
:+1:
