### ISSUE TITLE
Support for ES7 Property Initializers

### ISSUE THREAD

**Issue by jacowley** [h13i32maru/esdoc#25]
I know in the FAQ it says ES7 is not supported, but many people are now making use of this feature e.g. http://babeljs.io/blog/2015/06/07/react-on-es6-plus/ using Babel.

Currently the doc generator fails if it encounters any property initialisers.

Is there any possibility you would consider adding support for this?

**Comment by h13i32maru** [comment]
@jacowley Hi! Thank you for question!

I want to support it in future.

But, now, I want to use my time for developing "ESDoc documentation hosting site (like [rubydoc.info](http://www.rubydoc.info) and [godoc.org](https://godoc.org))".

Sorry. 😔

**Comment by jacowley** [comment]
@h13i32maru No worries. Thanks for the reply. It would be nice to have, but not essential. There are other tools that I use that don't support them yet anyway so I'll have to be patient :)

**Comment by h13i32maru** [comment]
@jacowley 
I published [ESDoc ES7 Plugin](https://github.com/esdoc/esdoc-es7-plugin) :smile:
This plugin enables to generate documentation from source code including ES7.
You can use this plugin with ESDoc@0.2.1
