### ISSUE TITLE
support complex class extends.

### ISSUE THREAD

**Issue by h13i32maru** [h13i32maru/esdoc#26]
support complex class extends.
- expression extends
  - ``class Foo extends Bar(123) {}``
- mixin extends
  - ``class Foo extends mix(Bar, Baz){}``

**Comment by h13i32maru** [comment]
<img width="570" alt="2015-07-12 16 18 48" src="https://cloud.githubusercontent.com/assets/985170/8636852/bf155dbc-28b1-11e5-87be-2eee136664af.png">

<img width="667" alt="2015-07-12 16 18 33" src="https://cloud.githubusercontent.com/assets/985170/8636854/c2638318-28b1-11e5-853d-de5fdc28bc97.png">

**Comment by mysticatea** [comment]
Awesome!

**Comment by h13i32maru** [comment]
thanks :sparkles:
