### ISSUE TITLE
Plugin feature

### ISSUE THREAD

**Issue by h13i32maru** [h13i32maru/esdoc#27]
Plugin provides some hook point. And users can customize data at hook points.
- after reading config file, and customize config object.
- after reading source code file, and customize source code.
- after reading source code file, and use own JavaScript parse(must compatible Espree)
- after parsing source code file, and customize AST.
- after parsing documentation tag, and customize documentation object.
- after building HTML, and customize HTML.

**config**
```json
{
  "source": "./src",
  "destination": "./esdoc",
  "plugins": [
    {"name": "foo-esdoc-plugin", "option": {}},
    {"name": "./bar-esdoc-plugin.js", "option": {}}
  ]
}
```
**plugin**
```javascript
exports.onStart = function(ev){...};
exports.onHandleConfig = function(ev){...};
exports.onHandleCode = function(ev){...};
exports.onHandleCodeParser = function(ev){...};
exports.onHandleAST = function(ev){...};
exports.onHandleTag = function(ev){...};
exports.onHandleHTML = function(ev){...};
exports.onComplete = function(ev){...};
```

**Comment by mysticatea** [comment]
Cool.

How about publishing of plugins with npm similar to babel or eslint?
For example, we can [install eslint-plugin-react with npm](https://github.com/yannickcr/eslint-plugin-react#installation).

**Comment by h13i32maru** [comment]
@mysticatea Thank you!
ESLint plugin system is nice :+1: 

I consider below.

```json
{
  "source": "./src",
  "destination": "./esdoc",
  "plugins": ["foo-esdoc-plugin", "./bar-esdoc-plugin.js"]
}
```

- ``foo-esdoc-plugin`` is loaded from local ``node_modules``
- ``./bar-esdoc-plugin.js`` is loaded from local file.

So, internal code is 
```javascript
for (let pluginName of config.plugins) {
  let plugin = require(pluginName);
}
```

**Comment by mysticatea** [comment]
:+1:

**Comment by h13i32maru** [comment]
I create plugin feature :rocket:
