### ISSUE TITLE
Only one @example rendered?

### ISSUE THREAD

**Issue by yamalight** [h13i32maru/esdoc#28]
Looks like only one `@example` tag is rendered into HTML.
It also looks like esdoc doesn't do anything with [optional](http://usejsdoc.org/tags-example.html) `<caption>` tag.

**Comment by h13i32maru** [comment]
ESDoc supports multi ``@example``.

And I want to support ``<caption>`` tag in future version.

<img width="299" alt="2015-07-15 22 33 05" src="https://cloud.githubusercontent.com/assets/985170/8699593/90d50f1e-2b41-11e5-91c7-a7c2985bccc0.png">
<img width="310" alt="2015-07-15 22 33 22" src="https://cloud.githubusercontent.com/assets/985170/8699594/90d815e2-2b41-11e5-9f53-8f95c7c99c5d.png">

**Comment by yamalight** [comment]
hm, that's a bit weird, gonna check my code once more I guess. thanks!

**Comment by h13i32maru** [comment]
If this issue occur again, please post your code 🙋

**Comment by yamalight** [comment]
okay, looks like it was me being blind and not noticing two example one right after the other 
maybe it's worth considering to append "Example:" header before each snippet?

but all works as expected, so I'll close this issue.

**Comment by h13i32maru** [comment]
> considering to append "Example:" header before each snippet?

Sorry, for now, I am not going to it.
But I will make following style with ``<caption>`` tag.

<img width="376" alt="2015-07-19 9 28 16" src="https://cloud.githubusercontent.com/assets/985170/8764067/9f8af226-2df8-11e5-9102-e02ec85f3a98.png">

**Comment by yamalight** [comment]
@h13i32maru that looks sweet! :+1:
