### ISSUE TITLE
Question about ES6+ support/willingness to accept PRs

### ISSUE THREAD

**Issue by mmoss** [h13i32maru/esdoc#29]
Hey there, I know you don't currently support ES6+ (or ES7) features, since they're still under development/review. However, I've run into issues where using these new features causes esdoc to fail silently. Would you be amenable to a pull request to opt-into, or to ignore, ES6+ features, so that other files can still be processed? I've looked into this already, and it may also require a fix to espree (which I would submit prior to any PR for this project).

Thanks,
Murray

**Comment by h13i32maru** [comment]
@mmoss Thanks question!

I welcome pull-request that is ignore ES6+ features :smile: 
However, Espree does not seem to support ES6+.
So, this work is hard for me :sweat: 

And, for now, I am not going to merge ES6+ feature pull request. Sorry.

**Comment by mysticatea** [comment]
Actually, espree supports ES7 Rest/Spread Properties (stage 1) experimentally.
But currently espree seems to have no plan to support more. :cry:

**Comment by h13i32maru** [comment]
@mysticatea oh...
ES7 support is very hard for everyone.
(Babel and @sebmck is special!)

**Comment by mmoss** [comment]
I'll take a stab at adding the ability to ignore ES7 features (at least decorators), or at the very least try and figure out a way to output a warning if a file is ignored due to ES7 syntax preventing parsing.

**Comment by benmosher** [comment]
FWIW, [babel-eslint] is essentially an Esprima-/Espree-compatible parser that uses Babel under the covers, but returns an Espree-like AST. (it's intent is only to support ESLint, but I suspect it might be generally useful as a mostly-Esprima-compatible parser)

[babel-eslint]: https://github.com/babel/babel-eslint

One option: provide a setting to configure an alternate parser (like ESLint does) and let users attempt to use ES7+ features at their own peril. You can then continue to default to (and only officially support) Espree, but users/potential committers can play around on the bleeding edge.

Pending your tolerance for non-ESTree/SpiderMonkey node types (things like `ExportNamespaceSpecifier` from Lee Byron's import/export symmetry proposal: `export * as ns from 'module'`), it may be as simple as dropping in the `parser` config option.

**Comment by h13i32maru** [comment]
@mmoss @benmosher Thanks :smile: 

I am considering plugin feature #27 . The plugin provides ``onHandleCodeParser`` to use own JavaScript parser. The parser must be compatible with Espree.

```javascript
exports.onHandleCodeParser = function(event) {
  var code = event.code;
  var ast = yourParser.parse(code);
  event.ast = ast;
}
```

And, with this feature, it becomes possible with TypeScript and other transpile language not only ES7.

**Comment by PinkaminaDianePie** [comment]
i tried to use esdoc, but it fails on files with es7 syntax (i am using async/await + decorators + property initializers), so i was forced to switch on yuidoc. It will be nice to see possibility to use another js parsers, such babel.

**Comment by h13i32maru** [comment]
@PinkaminaDianePie Thanks for comment! I will try to provide the plugin feature :rocket:

**Comment by mmoss** [comment]
@h13i32maru let me know if I can help out in any way :)

**Comment by h13i32maru** [comment]
@mmoss Thank you!

**Comment by h13i32maru** [comment]
@mmoss @benmosher @PinkaminaDianePie @mysticatea Hi!
I published [ESDoc ES7 Plugin](https://github.com/esdoc/esdoc-es7-plugin) :smile:
This plugin enables to generate documentation from source code including ES7.
You can use this plugin with ESDoc@0.2.1

**Comment by PinkaminaDianePie** [comment]
@h13i32maru, cool, thx! Ill try it tomorrow, i hope ill move out from yui. One more question: esdoc supports markdown? Or maybe custom templates, where i can switch from html to markdown? its usefull feature for easier integration to github-pages site, created from markdown via jekyll. I can use same styles for manual docs and for auto-generated.

**Comment by h13i32maru** [comment]
@PinkaminaDianePie ESDoc does not support markdown documentation. However, you can perhaps generate it by using [plugin feature](https://esdoc.org/api.html#plugin-feature). But I think that it is very hard work...

On the other hand, I have been developing [ESDoc Hosting Service](https://doc.esdoc.org/).
In there, you can generate your documentation and host it. Please try it if it is good for you :smile:

**Comment by PinkaminaDianePie** [comment]
I was tried to use esdoc with es7 plugin, but it does not help T_T I thought what only es7 features will be ignored or maybe async functions will be parsed like es5 functions but... any code uses es7 will be ignored, so if i use async function in my class - entire class will be ignored. So almost nothing was generated. Sad. And some code still crushes esdoc, i dont know exacly where for now

**Comment by h13i32maru** [comment]
@PinkaminaDianePie The plugin requires ESDoc version 0.2.1. Do you use the version?
If it is ok, please tell me your code or repository url.

The plugin supports async/await of ES7 following code.
```javascript
export class ES7AsyncFunctions {
  async method(){
    await Promise.revole(1);
  }
}
```

FYI: https://doc.esdoc.org/github.com/esdoc/esdoc-hosting-safe-plugin/class/src/ES7/ES7AsyncFunctions.js~ES7AsyncFunctions.html

**Comment by PinkaminaDianePie** [comment]
@h13i32maru, oh, im sorry, thx for answer! There was something with my global modules, even after install v0.1.2 was used. For now everything is ok. Ok, ill see what can i use for my docs, maybve it will be better than yui

**Comment by h13i32maru** [comment]
@PinkaminaDianePie :+1:
