### ISSUE TITLE
Esdoc skips objects/functions exported using `export {myThing}`

### ISSUE THREAD

**Issue by yamalight** [h13i32maru/esdoc#30]
So, if you have the following snippet:
```js
/**
 * Test function
 * @return {void}
 */
const TestFunction = function() {
    console.log('test');
};

export {TestFunction};
```
Esdoc will not generate any documentation for this.

But if you change it to this:
```js
/**
 * Test function
 * @return {void}
 */
export const TestFunction = function() {
    console.log('test');
};
```
It'll work as expected.

This does not affects Classes - for them everything is generated OK for both cases.

**Comment by h13i32maru** [comment]
Thanks issue!

This is ESDoc bug :sweat:

**Comment by h13i32maru** [comment]
ESDoc supports separate function and variable export.

**Comment by yamalight** [comment]
awesome, thanks! :+1:
