### ISSUE TITLE
Inheritance output fails when module file name contains additional dots e.g. my.class.js

### ISSUE THREAD

**Issue by cdimascio** [h13i32maru/esdoc#31]
1. Follow the tutorial here: https://esdoc.org/tutorial.html
2. Instead of naming the files MySuperClass.js and MyClass.js, name them my.super.class.js and my.class.js, respectively,
3. Review the output HTML for MyClass e.g. my.class.js~MyClass.html
4. See that the Inheritance summary and override methods are missing

All in all, additional dots '.' in the filename break the inheritance functionality.

**Comment by h13i32maru** [comment]
@cdimascio Thanks issue!
I will fix this issue in future version.

**Comment by h13i32maru** [comment]
@cdimascio If you write the below code, you must also change also import path.
```javascript
import MySuperClass from './MySuperClass.js';

export default class MyClass extends MySuperClass {
...
}
```

to

```javascript
import MySuperClass from './my.super.class.js';

export default class MyClass extends MySuperClass {
...
}
```
