### ISSUE TITLE
Grunt support?

### ISSUE THREAD

**Issue by ariporad** [h13i32maru/esdoc#32]
Hi!

I was wondering if grunt support was on the roadmap for this project? For me at least it's a must.

I'm not really sure how complex it is to integrate with grunt, the grunt-jsdoc plugin seems rather complex. If it's simplish, I'd be happy to do it myself.

I think it can be done with the programmatic API, but I can't figure out how that works. If I could get some more info, on the API, I'd be happy to whip up a plugin.

Thanks!

**Comment by h13i32maru** [comment]
@ariporad Hi! Thanks question!
Sorry, I do not plan to support grunt.

The following code may help you for making grunt plugin.

```javascript
var ESDoc = require('esdoc/out/src/ESDoc.js');
var publisher = require('esdoc/out/src/Publisher/publish.js');
var config = {source: './src', destination: './doc'};

ESDoc.generate(config, publisher);
```

But this code may not work in future version.

FYI: ESDoc gulp plugin https://www.npmjs.com/package/turris-gulp-tasks

**Comment by cleversoap** [comment]
I ended up on this question when looking at integrating ESDoc into a project that uses grunt so I knocked up a quick plugin for it: https://github.com/cleversoap/grunt-esdoc

ESDoc looks pretty great so I'm sure I'll still be using it when / if the code changes and I'll update my plugin accordingly but at this point it works with the current version (0.1.4)

**Comment by h13i32maru** [comment]
@cleversoap Thanks for creating the grunt plugin and it is great work :sparkles:
