### ISSUE TITLE
Handle ES7 decorators

### ISSUE THREAD

**Issue by stremlenye** [h13i32maru/esdoc#35]
Decorators become quite wide spread for time annotation or library features deprecation (thanks `babel`).
So is it possible to support them in `esdoc`.
Currently classes, which contains decorated methods are excluded out of the output.

```js
//wouldn't be included in documentation
class A {
  @bar
  foo () {
    …
  }
}
```

**Comment by h13i32maru** [comment]
@stefanwalther Hi! Thanks for this issue :smile: 
But, I don't have plan to support ES7. Please see https://github.com/h13i32maru/esdoc/issues/29 for more information.

**Comment by h13i32maru** [comment]
@stremlenye Hi!
I published [ESDoc ES7 Plugin](https://github.com/esdoc/esdoc-es7-plugin) :smile:
This plugin enables to generate documentation from source code including ES7.
You can use this plugin with ESDoc@0.2.1

**Comment by stremlenye** [comment]
@h13i32maru Great! Thank you!
I'll try it soon and provide feedback.
But anyway that awesome!

**Comment by h13i32maru** [comment]
:+1:
