### ISSUE TITLE
ES7 static property initializers causes esdoc errors

### ISSUE THREAD

**Issue by jasonsanjose** [h13i32maru/esdoc#37]
https://esdiscuss.org/topic/es7-property-initializers

```
export class Counter extends React.Component { 
    static propTypes = { 
        initialCount: React.PropTypes.number
    }; 
...
```

Similar to #36, esdoc should at least silently ignore unexpected syntax and continue generating documentation.

**Comment by h13i32maru** [comment]
@jasonsanjose Please see https://github.com/h13i32maru/esdoc/issues/36#issuecomment-126872223
