### ISSUE TITLE
Separate class definition and export statement

### ISSUE THREAD

**Issue by koba04** [h13i32maru/esdoc#6]
When I separate class definition and export statement, class definition doesn't show in Identifier. 

* ok

```js
/**
 * this is MyClass.
 */
export default class MyClass {
 /**
 * @param {number} param this is param.
 * @return {number} this is return.
 */
  method(param){}
}
```

* ng

```js
/**
 * this is MyClass.
 */
class MyClass {
 /**
 * @param {number} param this is param.
 * @return {number} this is return.
 */
  method(param){}
}
export default MyClass;
```

Do you have a plan that support this case?

**Comment by h13i32maru** [comment]
@koba04 ESDoc has been supported in the NG case. Thank you for this issue :smile:

**Comment by koba04** [comment]
@h13i32maru awesome!!! :laughing: Thank you for your great work!
