### ISSUE TITLE
6sec hangup when opened by `file://` protocol.

### ISSUE THREAD

**Issue by mysticatea** [h13i32maru/esdoc#8]
Hello!

esdoc is the great tool!
But it seems frozen during about 6 seconds when opened as the local file.

I guess the cause is [this](https://github.com/h13i32maru/esdoc/blob/62e8da2f6970aed54f16f2f3dac139c4a0b6c487/src/Publisher/Builder/template/css/style.css#L1).
It's waiting for a timeout of opening `file://fonts.googleapis.com`.
So I think we can use `https://fonts.googleapis.com/css?family=Roboto:400,300,700` instead.

Thanks.

```
GET file://fonts.googleapis.com/css?family=Roboto:400,300,700 net::ERR_FILE_NOT_FOUND
```

![devtools timeline](https://cloud.githubusercontent.com/assets/1937871/7900485/164f8c16-0796-11e5-9275-20ed83297a9a.png)

----

- ESDoc `v0.1.1`
- Node `v0.12.2`
- npm `v2.8.4`
- Windows 7 Pro 64bit

**Comment by h13i32maru** [comment]
@mysticatea Hello! Thank you for using ESDoc.
The hangup is not occur in my environment(Mac OSX10.10.3 & Chrome42). 
However, I think that your proposal is correct.
So I fixed web font protocol and will release the fixing in next version.

**Comment by mysticatea** [comment]
Thank you.
I updated esdoc and received the fix!
